### ISSUE TITLE
Amélioration doc partie3

### ISSUE THREAD

**Issue by bil44** [mickeys27/Docs#62]
Bonjour,
Dans la partie 3 de la doc  : https://github.com/mickeys27/Docs/blob/master/conso/fr_FR/partie_3.md , et concernant la modification des fréquences dans le cron:
J'ajouterais :  les modifications ne sont prise en compte qu'après une relance du plugin suiviconso.
Même ci cela semble évident pour les linuxiens !
D'avance merci

**Comment by superbricolo** [comment]
J'ai ajouté les modifs de doc
